# All configuration options can be referred from:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # Yarn ecosystem is tracked under keyword npm
    directory: "/" # package.json exists on root location
    schedule:
      interval: "monthly" # Get montly updates
    labels:
      - "dependencies" # Have label 'dependencies' for PR raised by Dependabot
    reviewers:
       - "bhavik2936" # Ask for review of the repo owner
